# Generated by Django 6.0.6 on 2026-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_system', '0003_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
