# Generated by Django 6.0.6 on 2026-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_system', '0004_sessionnote_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
