# Generated by Django 6.0.6 on 2026-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Offline', 'Offline'), ('On Leave', 'On Leave')], default='Available', max_length=20),
        ),
    ]
