# Generated by Django 6.0.6 on 2026-07-06 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Calm', 'Calm'), ('Neutral', 'Neutral'), ('Sad', 'Sad'), ('Stressed', 'Stressed'), ('Anxious', 'Anxious')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moods',
            },
        ),
    ]
