# Generated by Django 6.0.6 on 2026-07-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
